name: CI Pipeline  
  
on:  
  pull_request:  
    type: [ opened, synchronize ]
  push:    

concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true  
  
jobs:  
  ci-pipeline:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout  
        uses: actions/checkout@v2   

      - name: Setup Python  
        uses: actions/setup-python@v2  
        with:  
          python-version: 3.9.2  
          architecture: x64  
          cache: 'pip'

      - name: Install dependencies  
        run: pip install -r requirements.txt

      - name: Run flake8  
        run: flake8 src/

      - name: Run mypy  
        run: mypy src/

      - name: Run pytest  
        run: pytest tests
        